/* eslint-disable @typescript-eslint/no-empty-object-type */
/* eslint-disable @typescript-eslint/no-empty-interface */

import type { PaletteColor, PaletteColorOptions } from '@mui/material/styles'

/**
 * Material You palette keys generated by this library (in addition to the standard MUI keys).
 *
 * Note:
 * - We intentionally augment the PUBLIC module '@mui/material/styles' to make it resilient to
 *   different TS moduleResolution modes ('bundler', 'node16', etc.) and MUI internal refactors.
 * - Keep these keys in sync with what your createMaterialYouTheme() actually puts into theme.palette.
 */
declare module '@mui/material/styles' {
  interface MaterialYouPalette {
    // Standard MUI keys (primary/secondary/error/background/...) are intentionally omitted here.

    onPrimary: PaletteColor
    primaryContainer: PaletteColor
    onPrimaryContainer: PaletteColor

    onSecondary: PaletteColor
    secondaryContainer: PaletteColor
    onSecondaryContainer: PaletteColor

    tertiary: PaletteColor
    onTertiary: PaletteColor
    tertiaryContainer: PaletteColor
    onTertiaryContainer: PaletteColor

    onError: PaletteColor
    errorContainer: PaletteColor
    onErrorContainer: PaletteColor

    onBackground: PaletteColor

    surface: PaletteColor
    onSurface: PaletteColor

    surfaceVariant: PaletteColor
    onSurfaceVariant: PaletteColor

    outline: PaletteColor
    outlineVariant: PaletteColor

    shadow: PaletteColor
    scrim: PaletteColor

    inverseSurface: PaletteColor
    inverseOnSurface: PaletteColor
    inversePrimary: PaletteColor

    primaryFixed: PaletteColor
    onPrimaryFixed: PaletteColor
    primaryFixedDim: PaletteColor
    onPrimaryFixedVariant: PaletteColor

    secondaryFixed: PaletteColor
    onSecondaryFixed: PaletteColor
    secondaryFixedDim: PaletteColor
    onSecondaryFixedVariant: PaletteColor

    tertiaryFixed: PaletteColor
    onTertiaryFixed: PaletteColor
    tertiaryFixedDim: PaletteColor
    onTertiaryFixedVariant: PaletteColor

    surfaceTint: PaletteColor
    surfaceDim: PaletteColor
    surfaceBright: PaletteColor
    surfaceContainerLowest: PaletteColor
    surfaceContainerLow: PaletteColor
    surfaceContainer: PaletteColor
    surfaceContainerHigh: PaletteColor
    surfaceContainerHighest: PaletteColor

    onInfo: PaletteColor
    infoContainer: PaletteColor
    onInfoContainer: PaletteColor

    onSuccess: PaletteColor
    successContainer: PaletteColor
    onSuccessContainer: PaletteColor

    onWarning: PaletteColor
    warningContainer: PaletteColor
    onWarningContainer: PaletteColor
  }

  interface MaterialYouPaletteOptions {
    onPrimary?: PaletteColorOptions
    primaryContainer?: PaletteColorOptions
    onPrimaryContainer?: PaletteColorOptions

    onSecondary?: PaletteColorOptions
    secondaryContainer?: PaletteColorOptions
    onSecondaryContainer?: PaletteColorOptions

    tertiary?: PaletteColorOptions
    onTertiary?: PaletteColorOptions
    tertiaryContainer?: PaletteColorOptions
    onTertiaryContainer?: PaletteColorOptions

    onError?: PaletteColorOptions
    errorContainer?: PaletteColorOptions
    onErrorContainer?: PaletteColorOptions

    onBackground?: PaletteColorOptions

    surface?: PaletteColorOptions
    onSurface?: PaletteColorOptions

    surfaceVariant?: PaletteColorOptions
    onSurfaceVariant?: PaletteColorOptions

    outline?: PaletteColorOptions
    outlineVariant?: PaletteColorOptions

    shadow?: PaletteColorOptions
    scrim?: PaletteColorOptions

    inverseSurface?: PaletteColorOptions
    inverseOnSurface?: PaletteColorOptions
    inversePrimary?: PaletteColorOptions

    primaryFixed?: PaletteColorOptions
    onPrimaryFixed?: PaletteColorOptions
    primaryFixedDim?: PaletteColorOptions
    onPrimaryFixedVariant?: PaletteColorOptions

    secondaryFixed?: PaletteColorOptions
    onSecondaryFixed?: PaletteColorOptions
    secondaryFixedDim?: PaletteColorOptions
    onSecondaryFixedVariant?: PaletteColorOptions

    tertiaryFixed?: PaletteColorOptions
    onTertiaryFixed?: PaletteColorOptions
    tertiaryFixedDim?: PaletteColorOptions
    onTertiaryFixedVariant?: PaletteColorOptions

    surfaceTint?: PaletteColorOptions
    surfaceDim?: PaletteColorOptions
    surfaceBright?: PaletteColorOptions
    surfaceContainerLowest?: PaletteColorOptions
    surfaceContainerLow?: PaletteColorOptions
    surfaceContainer?: PaletteColorOptions
    surfaceContainerHigh?: PaletteColorOptions
    surfaceContainerHighest?: PaletteColorOptions

    onInfo?: PaletteColorOptions
    infoContainer?: PaletteColorOptions
    onInfoContainer?: PaletteColorOptions

    onSuccess?: PaletteColorOptions
    successContainer?: PaletteColorOptions
    onSuccessContainer?: PaletteColorOptions

    onWarning?: PaletteColorOptions
    warningContainer?: PaletteColorOptions
    onWarningContainer?: PaletteColorOptions
  }

  // Merge into MUI palette types
  interface Palette extends MaterialYouPalette {}
  interface PaletteOptions extends MaterialYouPaletteOptions {}
}

export {}
